### ISSUE TITLE
Token exfiltration by malicious server

### ISSUE THREAD

**Issue by randomstuff** [aaronpk/oauth-authorization-server-location-response#2]
The draft [discusses a fishing attack](https://www.ietf.org/archive/id/draft-parecki-oauth-authorization-server-discovery-00.html#name-phishing) where a malicious resource server redirects the user to a fake malicious authorization server in order to obtain the user's credentials.

Another attack scenario is when a malicious server announces a valid Authorization Server in order to exfiltrate a user's access token:

1. user points its client application to `https://evil/`;
2. the user's client makes a request to ``https://evil/`;
3. the evil server responds with `WWW-Authenticate: ... issuer="https://as"`;
4. the client initiates a OAuth flow with the (valid) authorization server;
5. the client obtains an access token from the authorization server;
6. the clients sends this access token to the authorization server;
7. the malicious server can use the access token;

Some extra steps/verifications/parameters would be needed in order to ensure that the issued access token's audience are properly scoped to the requesting resource server.

**Comment by aaronpk** [comment]
This spec has been incorporated and replaced by Protected Resource Metadata. This issue is covered in the security considerations:

https://www.ietf.org/archive/id/draft-ietf-oauth-resource-metadata-13.html#name-audience-restricted-access-
